version: "3.8"

services:
  nextjs:
    build: .
    command: npm run start
    container_name: nextjs_app
    restart: always
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=https://nsaelmgrsgpafxalwrge.supabase.co
      - NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=sb_publishable_p2bpFo9d_GnUeIyz8U7a8A_XFD82PFC
      - NEXT_PUBLIC_ADMIN_KEY=dcodeallstars7
    networks:
      - app_network

  # duckdns:
  #   image: linuxserver/duckdns
  #   container_name: duckdns
  #   restart: always
  #   environment:
  #     - SUBDOMAINS=mindmaze.duckdns.org
  #     - TOKEN=4b02543a-bf37-43f3-b705-e896770366bd
  #   networks:
  #     - app_network

networks:
  app_network:
